import os
import sys

vector_source = ""

vector_source += "# generated by vectors.pl - do not edit\n"
vector_source += "# handlers\n"
vector_source += ".globl alltraps\n"

for i in range(256):
    vector_source +=  f".globl vector{i}\n"
    vector_source +=  f"vector{i}:\n"
    if(not (i == 8 or (i >= 10 and i <= 14) or i == 17)):
        vector_source +=  "  pushl $0\n"
    
    vector_source +=  f"  pushl ${i}\n"
    vector_source +=  "  jmp alltraps\n"



vector_source += "\n# vector table\n"
vector_source += ".data\n"
vector_source += ".globl vectors\n"
vector_source += "vectors:\n"
for i in range(256):
   vector_source += f"  .long vector{i}\n"

with open(sys.argv[1],'w') as f:
    print(f"Write vector source file {sys.argv[1]}")
    f.write(vector_source)
